version: "3.4"
services:
    api:
        build:
            context: ./
            target: "production-stage"
        image: ali/express:4.x
        container_name: apfn-stores-api
        restart: unless-stopped
        ports:
            - 3005:${APP_PORT}
        volumes:
            - ./:/app
            - /app/node_modules
        env_file:
            - .env.production

networks:
    default:
        external: true
        name: webproxy
