version: "3.5"
services:
    api:
        build:
            context: ./
            target: "development-stage"
        image: ali/express:4.x
        container_name: apfn-stores-api-dev
        restart: unless-stopped
        ports:
            - 3000:${APP_PORT}
        volumes:
            - ./:/app
            - /app/node_modules
        env_file:
            - .env.development
